server:
  port: 9494

spring:
  config:
    import: "configserver:${SPRING_CONFIG_SERVER_ADDRESS:http://localhost:9292/}"
  application:
    name: organization-service
  profiles:
    active: "${SPRING_ACTIVE_PROFILE:local}"
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/stocks-realm

logging:
  level:
    root: info
    org.springframework.security: debug
    net.dmly: debug
